language: java

before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22.6.1-linux.tgz
    - tar xzf android-sdk_r22.6.1-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    # install android build tools
    - wget https://dl-ssl.google.com/android/repository/build-tools_r19.0.3-linux.zip
    - unzip build-tools_r19.0.3-linux.zip -d $ANDROID_HOME
    - mkdir -p $ANDROID_HOME/build-tools/
    - mv $ANDROID_HOME/android-4.4.2 $ANDROID_HOME/build-tools/19.0.3

    # Install required Android components.
    - echo y | android update sdk --filter platform-tools,android-19,extra-android-support --no-ui --force

